import { Baloo_2 } from 'next/font/google';

import Modal from '~/components/Modal';
import { RequestErrorTemplate } from '~/components/Modal/templates/RequestError';

import '~/styles/global.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const baloo2 = Baloo_2({
  weight: ['400', '500', '600', '700', '800'],
  fallback: ['cursive'],
  subsets: ['latin'],
  variable: '--font-baloo-2',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={baloo2.variable}>
        {children}

        <div id="modal-root" />

        <Modal id="modal-error">
          <RequestErrorTemplate />
        </Modal>
      </body>
    </html>
  );
}
